import {  TermObject } from "./deckObject";


export const anatomicalTerms: TermObject = {
  "anatomy" : "the study of the structure of the body",
  "physiology" : "the study of the function of the body",
  "developmental" : "studies structure changes from fertilization to death",
  "gross" : "structures that can be examined without using a microscope",
  "regional" : "specific regions of the body such as head or chest",
  "systemic" : "structure of specific body systems such as nervous or respiratory",
  "surface" : "external features",
  "microscopic" : "structures that need a microscope to view",
  "complementarity" : "when function reflects structure",
  "principle of complementarity" : "what a structure can do depends on its specific form",
  "chemical" : "level of organization: atoms and molecules",
  "cellular" : "level of organization: molecules that combine",
  "tissue" : "level of organization: groups of cells that work together to perform a specific function",
  "organ" : "level of organization: structures composed of at least two types of tissues",
  "organ system" : "level of organization: related organs with a common function",
  "organismal" : "level of organization: a whole living individual",
  "integumentary" : "body system: skin & structures associated with it",
  "skeletal" : "body system: bones & joints",
  "muscular" : "body system: brings about body movements",
  "nervous" : "body system: brain, spinal cord & nerves",
  "endocrine" : "body system: hormone-producing glands & cells",
  "cardiovascular" : "body system: blood, heart & vessels",
  "lymphatic" : "body system: fluid, vessels & cells associated with immune response",
  "respiratory" : "body system: lungs & air passageways",
  "digestive" : "body system: physical & chemical breakdown of food",
  "urinary" : "body system: eliminates waste & regulates chemical composition of blood",
  "reproductive" : "body system: gonads & associated organs",
  "coronal" : "vertical body plane that divides body into front and back ('crown')",
  "frontal" : "vertical body plane that divides body into front and back ('not crown')",
  "transverse" : "horizontal body plane that divides body into top and bottom",
  "median" : "vertical body plane that divides body into equal left and right sides ('half')",
  "midsagittal" : "vertical body plane that divides body into equal left and right sides ('arrow')",
  "sagittal" : "vertical body plane that divides body into left and right sides ('arrow')",
  "paramedian" : "vertical body plane that divides body into unequal left and right sides ('half')",
  "parasagittal" : "vertical body plane that divides body into unequal left and right sides ('arrow')",
  "oblique" : "body plane that passes through on an angle",
  "superior" : "towards the head ('better')",
  "inferior" : "away from head ('not as good')",
  "cranial" : "towards the head (fancy)",
  "caudal" : "away from head (towards tail)",
  "anterior" : "towards front of body",
  "posterior" : "towards back of body",
  "ventral" : "front of body (fish)",
  "dorsal" : "back of body (fish)",
  "superficial" : "on the surface",
  "intermediate" : "between superficial and deep",
  "deep" : "structure farther away from the surface",
  "proximal" : "towards the origin or towards trunk",
  "distal" : "away from origin or away from trunk",
  "medial" : "closer to midline",
  "lateral" : "farther from midline",
  "axial skeleton" : "head neck & trunk",
  "appendicular skeleton" : "upper/lower limbs",
  "anatomical position" : "standing erect, palms/feet/face/eyes facing forward, arms at sides",
  "cephalic" : "head",
  "cervical" : "neck",
  "upper limb" : "arm",
  "lower limb" : "leg",
  "trunk" : "thorax, abdomen, pelvis",
  "pedal" : "foot",
  "hand dorsal surface" : "back of hand (3 words)",
  "hand dorsum" : "back of hand (2 words)",
  "palmar surface" : "palm",
  "foot dorsal surface" : "top of foot (3 words)",
  "foot dorsum" : "top of foot (2 words)",
  "plantar surface" : "sole of foot",
  "smooth muscle" : "what types of cells work together in small intenstine to push food through",
  "epithelial, smooth muscle, connective" : "what types of tissues make up blood vessel (from inside to out)",
  "deviated" : "we use anatomical position to explain what type of positions",
  "thumb" : "best hand element to check which way palms are facing",
  "forward" : "the direction hands face in anatomical position",
}

export const bodyPartMovements = {
  "flexion at hip" : "leg goes forward",
  "extension at hip" : "leg goes backward",
  "flexion at shoulder" : "arm goes forward",
  "extension at shoulder" : "arm goes backward",
  "flexion at elbow" : "arm bend that brings hand closer to shoulder",
  "extension at elbow" : "arm un-bend that brings hand farther from shoulder",
  "flexion at knee" : "leg bend that makes foot go up to back",
  "extension at knee" : "leg un-bend that makes foot go down",
  "flexion of vertebral column" : "body tilts forward",
  "extension of vertebral column" : "body tilts back",
  "flexion at wrist" : "arm in pronation, hand moves down",
  "extension at wrist" : "arm in pronation, hand moves up",
  "flexion of fingers" : "fingers curl in",
  "extension of fingers" : "fingers extend straight after curling",
  "opposition" : "thumb and pinky fingers come together",
  "reposition" : "opposition movement released",
  "lateral abduction" : "middle finger tilts towards thumb",
  "medial abduction" : "middle finger tilts towards pinky",
  "abduction of fingers" : "spread fingers wide",
  "adduction of fingers" : "fingers come together (neutral)",
  "abduction of thumb" : "thumb goes forward",
  "adduction of thumb" : "thumb goes in (neutral)",
  "extension of thumb" : "thumb goes out to side",
  "flexion of thumb" : "thumb curls into palm",
  "elevation" : "raise shoulders up",
  "depression" : "lower shoulders",
  "retrusion" : "jaw goes in",
  "protrusion" : "jaw goes out",
  "protraction of scapula" : "arms go forward and hunch shoulders forward",
  "retraction of scapula" : "shoulders go way back",
  "dorsiflexion" : "flexing the foot upward",
  "plantarflexion" : "pointing the food downward",
  "flexion" : "motion that decreases joint angle",
  "extension" : "motion that increases joint angle",
  "adduction" : "move towards midline of body",
  "abduction" : "move away from midline of body",
  "lateral flexion" : "moving away from midline of body; bending sideways, fancy",
  "lateral bending" : "side bend, not fancy",
  "radial deviation" : "wrist tilt towards thumb",
  "ulnar deviation" : "wrist tilt towards pinky finger",
  "rotation" : "turning about the axis of the body",
  "medial rotation" : "internal rotation (incl. 'rotation')",
  "lateral rotation" : "external rotation (incl. 'rotation')",
  "supination" : "palms up",
  "pronation" : "palms down",
  "inversion" : "foot flexed and sickled inward (sole of foot faces midline)",
  "eversion" : "foot flexed and sickled outward (sole of foot faces away from midline)",
  "circumduction" : "circular movement of the lower limb at the hip joint",
}