export const lab1Terms = {
"cervical vertebrae" : "superior section of spine",
"7" : "number of vertebrae in cervical section",
"thoracic vertebrae" : "section of spine superior to lumbar & inferior to cervical",
"12" : "number of vertebrae in thoracic vertebrae",
"lumbar vertebrae" : "section of spine superior to sacral vertebrae",
"5" : "number of vertebrae in lower section of spine",
"sacral vertebrae" : "fused, inferior section of spine",
"sacrum" : "plate at inferior of spine",
"coccyx" : "most inferior structure of vertebral column",
"C1" : "code for most superior vertebrae",
"atlas" : "name for vertebrae with the biggest wings",
"C2" : "code for second most superior vertebrae",
"axis" : "name for vertebrae with dens",
"C7" : "superior-ish vertebrae with long projection",
"vertebral body" : "round-ish flat/filled section of vertebrae",
"dens" : "blip on C2",
"spinous process" : "projections of vertebrae that creates the spine (posterior projections)",
"transverse process" : "the lateral projections on vertebrae",
"superior articular process" : "side blips that hold spine together - side closest to head",
"inferior articular process" : "side blips that hold spine together - side farther from head",
"vertebral foramen" : "hole down middle of spine",
"frontal" : "anterior of superior skull",
"mandible" : "jaw bone",
"occipital" : "posterior of head",
"sphenoid" : "deep bone shaped like a mask (probably not testable)",
"vomer" : "vertical bone inside nose",
"zygomatic" : "cheek/eye cavity bone",
"nasal" : "bone on bridge of nose",
"maxilla" : "bone superior to mouth",
"temporal" : "bone inferior to parietal bone",
"parietal" : "most superior skull bone",
"manubrium" : "superior portion of sternum",
"body of sternum" : "vertical column of bone that connects ribs",
"xiphoid process" : "small projection on inferior end of sternum",
"rib" : "one of numerous projections on side of body",
"clavicle" : "bone superior to the ribs on anterior of body",
"glenoid fossa" : "cavity where humerus attaches",
"coracoid process" : "projection around glenoid fossa (anterior)",
"acromium process" : "superior, distal tip of scapula (posterior)",
"spine of scapula" : "long, outer projection on posterior side of scapula",
"posterior scapula" : "the side of the scapula where you can see its spine",
"anterior scapula" : "the side of the scapula where coracoid process projects outward"
}