export const lab1Terms = {
"cervical vertebrae" : "superior section of spine",
"7" : "number of vertebrae in cervical section",
"thoracic vertebrae" : "section of spine superior to lumbar & inferior to cervical",
"12" : "number of vertebrae in thoracic vertebrae",
"lumbar vertebrae" : "section of spine superior to sacral vertebrae",
"5" : "number of vertebrae in lower section of spine",
"sacral vertebrae" : "fused, inferior section of spine",
"sacrum" : "plate at inferior of spine",
"coccyx" : "most inferior structure of vertebral column",
"C1" : "code for most superior vertebrae",
"atlas" : "name for vertebrae with the biggest wings",
"C2" : "code for second most superior vertebrae",
"axis" : "name for vertebrae with dens",
"C7" : "superior-ish vertebrae with long projection",
"vertebral body" : "round-ish flat/filled section of vertebrae",
"dens" : "blip on C2",
"spinous process" : "projections of vertebrae that creates the spine (posterior projections)",
"transverse process" : "the lateral projections on vertebrae",
"superior articular process" : "side blips that hold spine together - side closest to head",
"inferior articular process" : "side blips that hold spine together - side farther from head",
"vertebral foramen" : "hole down middle of spine",
"frontal" : "anterior of superior skull",
"mandible" : "jaw bone",
"occipital" : "posterior of head",
"sphenoid" : "deep bone shaped like a mask (probably not testable)",
"vomer" : "vertical bone inside nose",
"zygomatic" : "cheek/eye cavity bone",
"nasal" : "bone on bridge of nose",
"maxilla" : "bone superior to mouth",
"temporal" : "bone inferior to parietal bone",
"parietal" : "most superior skull bone",
"manubrium" : "superior portion of sternum",
"body of sternum" : "vertical column of bone that connects ribs",
"xiphoid process" : "small projection on inferior end of sternum",
"rib" : "one of numerous projections on side of body",
"clavicle" : "bone superior to the ribs on anterior of body",
"glenoid fossa" : "cavity where humerus attaches",
"coracoid process" : "projection around glenoid fossa (anterior)",
"acromium process" : "superior, distal tip of scapula (posterior)",
"spine of scapula" : "long, outer projection on posterior side of scapula",
"posterior scapula" : "the side of the scapula where you can see its spine",
"anterior scapula" : "the side of the scapula where coracoid process projects outward"
}

export const lab2Terms = {
  "humerus" : "upper arm bone",
  "radius" : "lateral part of the forearm",
  "ulna" : "medial part of the forearm",
  "greater tubercle" : "large protrusion on superior end of humerus",
  "lesser tubercle" : "smaller protusion on superior end of humerus",
  "intertubercular groove" : "longer title version of the depression between two proximal protrusions on humerus",
  "bicipital groove" : "shorter title version of the depression between two proximal protrusions on humerus",
  "medial epicondyle of humerus" : "side bump on inferior end of humerus closest to midline",
  "lateral epicondyle of humerus" : "side bump on inferior end of humerus farthest from midline",
  "capitulum" : "anterior bump on distal end of humerus, medial to the lateral epicondyle, articulates with radius",
  "trochlea" : "anterior bump on distal end of humerus, lateral to the medial epicondyle, articulates with ulna",
  "head of radius" : "most proximal end of the forearm bone on thumb-side",
  "radial styloid process" : "small protusion on the distal end of the radius",
  "radial tuberosity" : "medial protrusion on the proximal end of the radius",
  "olecranon" : "large protrusion on the proximal end of the ulna",
  "ulnar styloid process" : "small protrusion on the distal end of the ulna",
  "carpals" : "the group of bones distal to the wrist",
  "scaphoid" : "most proximal & lateral carpal bone",
  "lunate" : "carpal bone that is between radius and ulna",
  "triquetrum" : "carpal bone that is against the ulna, but not the most medial",
  "pisiform" : "most medial proximal carpal bone",
  "trapezium" : "carpal bone attached to metatacarpal 1",
  "trapezoid" : "carpal bone attached to metatacarpal 2",
  "capitate" : "carpal bone attached to metacarpal 3",
  "hamate" : "carpal bone attached to metacarpal 4 & 5",
  "metacarpal 1" : "most lateral section of palm",
  "proximal phalanx of hand" : "most superior finger section in anatomical position",
  "distal phalanx of hand" : "most inferior finger section in anatomical postion",
  "middle phalanx of hand" : "section in finger that's between the proximal and distal area",
  "ilium" : "superior, posterior section of pelvis",
  "ischium" : "inferior, posterior section of pelvis",
  "pubis" : "anterior section of the pelvis",
  "pubic symphysis" : "cartilage section that joins the inferior pelvis together (the joining one)",
  "interpubic disc" : "cartilage section that joins the inferior pelvis together (the between one)",
  "anterior superior iliac spine" : "poke-ey protrusion at front of pelvis",
  "iliac crest" : "the superior, anterial surface on the top of the pelvis",
  "ischial tuberosity" : "posterior, inferior loop in pelvis",
  "head of femur" : "ball section of bone at superior end of femur",
  "neck of femur" : "narrowed bone section distal to the head of the femur",
  "greater trochanter" : "large protrusion at superior end of femur",
  "lesser trochanter" : "bump near superior end of femur, inferior to its partner",
  "lateral epicondyle of femur" : "bump on distal end of femur on outside of thigh",
  "medial epicondyle of femur" : "bump on distal end of femur on inside of thigh",
  "lateral condyle of femur" : "anterior bump on distal end of femur, closer to outside of thigh",
  "medial condyle of femur" : "anterior bump on distal end of femur, closer to inside of thigh",
  "medial condyle of tibia" : "large bump on inner, superior end of larger, lower leg bone",
  "lateral condyle of tibia" : "large bump on outer, superior end of larger, lower leg bone",
  "tibial tuberosity" : "bump on superior end of larger lower leg bone, inferior to the condyles",
  "medial malleolus" : "inferior tip of tibia",
  "tibia" : "medial lower leg bone",
  "fibula" : "lateral lower leg bone",
  "head of fibula" : "most superior tip of smaller leg bone",
  "lateral malleolus" : "most inferior tip of smaller leg bone",
  "calcaneous" : "heel bone",
  "talus" : "superior ankle bone",
  "navicular" : "bone in foot that joins the talus to the cuneiforms",
  "cuboid" : "bone in foot that is lateral to the cuneiforms",
  "lateral cuneiform" : "the bone that connects the navicular to metatarsal 3",
  "medial cuneiform" : "the bone that connects the navicular to metatarsal 1",
  "intermediate cuneiform" : "the bone that connects the navicular to metatarsal 2",
  "metatarsal 1" : "most medial section of ball of foot",
  "proximal phalanx of foot" : "most superior toe section in foot",
  "middle phalanx of foot" : "toe section in foot between proximal and distal ends",
  "distal phalanx of foot" : "most inferior toe section in foot"
}