export type ListObject = {
  [key: string]: [string[], string[], string];
};


export const mnemonics: ListObject = {
  // "Bones of the Arm": [["Ultra", "Red", "Hair"], ["Ulna", "Radius", "Humerus"], "ordered"],
  // "Bones of the Hand": [["Please", "Make", "Cookies"], ["Phalanges", "Metacarpal bones", "Carpal bones"], "ordered"],
  // "Rotator Cuff Muscles": [["Sit", "In", "The", "Seat"], ["Supraspinatus", "Infraspinatus", "Teres Minor", "Subscapularis"], "unordered"],
  // "Systems of the Body": [["M", "U", "R", "D", "E", "R", "S", "L", "I", "N", "C"], ["Muscular", "Urinary", "Respiratory", "Digestive", "Endocrine", "Reproductive", "Skeletal", "Lymphatic", "Integumentary", "Nervous", "Cardiovascular"], "unordered"],
  // "4 Functions of Epithelial Tissue" : [["P", "A", "S", "S"], ["physical protection", "absorption", "sensation", "secretion"], "unordered"],
  // "Epithelial Tissue Layers" : [["Any", "BS", "is BLatant", "Ridiculousness"], ["apical surface", "basal surface", "basal lamina" , "reticular lamina"], "ordered"],
  // "4 Types of Connective Tissue" : [["Please", "Call", "Back", "Beethoven"], ["connective tissue proper", "cartilage", "bone" , "blood"], "unordered"],
  // "6 Functions of Connective Tissue" : [["Steven", "Barely", "Sat", "Tonight", "Perchance", "I"], ["support", "binding", "storage" , "transport", "protection", "immune protection"], "unordered"],
  // "5 Types of Defence Cells" : [["Many", "Prissy", "Mothers", "Eat", "Nothing"], ["macrophage", "plasma", "mast" , "eosinophil", "neutrophil"], "unordered"],
  // "12 Shoulder Girdle Muscles": [["T", "R", "LD", "SA", "LS", "PM", "Pm", "D", "TM", "S", "I", "Sub"], ["trapezius", "rhomboids", "latissimus dorsi", "serratus anterior", "levator scapulae", "pectoralis major", "pectoralis minor", "deltoid", "teres major", "supraspinatus", "infraspinatus", "subscapularis"], "unordered"],
  // "8 arm muscles" : [["BBL", "BBS", "TBL", "TBM", "TBl", "C", "B", "BR"], ["biceps brachii long head", "biceps brachii short head", "triceps brachii long head", "triceps brachii medial head", "triceps brachii lateral head", "coracobrachialis", "brachialis", "brachioradialis"], "unordered"],
  // "8 anterior forearm muscles" : [["PT", "FCR", "PL", "FCU", "FDS", "FPL", "FDP", "PQ"], ["pronator teres", "flexor carpi radialis", "palmaris longus", "flexor carpi ulnaris", "flexor digitorum superficialis", "flexor pollicis longus", "flexor digitorum profundus", "pronator quadratus"], "ordered"],
  // "10 posterior forarm muscles" : [["ECRL", "ECRB", "ED", "ECU", "A", "S", "APL", "EPB", "EPL", "EI"], ["extensor carpi radialis longus", "extensor carpi radialis brevis", "extensor digitorum", "extensor carpi ulnaris", "anconeus", "supinator", "abductor pollicis longus", "extensor pollicis brevis", "extensor pollicis longus", "extensor indicis"], "ordered"],
  // "7 humerus features" : [["GT", "LT", "IG", "ME", "LE", "C", "T",], ["greater tubercle", "lesser tubercle", "intertubercular groove", "medial epicondyle of humerus", "lateral epicondyle of humerus", "capitulum", "trochlea"], "unordered"],
  // "5 radius and ulna features" : [["HR", "RSP", "RT", "O", "USP"], ["head of radius", "radial styloid process", "radial tuberosity", "olecranon", "ulnar styloid process"], "unordered"],
  // "12 wrist/hand features" : [["S", "L", "T", "P", "T", "To", "C", "H", "M", "PP", "DP", "MP"], ["scaphoid", "lunate", "triquetrum", "pisiform", "trapezium", "trapezoid", "capitate", "hamate", "metacarpal 1", "proximal phalanx of hand", "distal phalanx of hand", "middle phalanx of hand"], "unordered"],
  // "7 pelvic features" : [["Il", "Is", "P", "PS", "AS", "IC", "IT"], ["ilium", "ischium", "pubis", "pubic symphysis", "anterior superior iliac spine", "iliac crest", "ischial tuberosity"], "unordered"],
  // "8 femur features" : [["HF", "NF", "GT", "LT", "LE", "ME", "LCF", "MCF"], ["head of femur", "neck of femur", "greater trochanter", "lesser trochanter", "lateral epicondyle of femur", "medial epicondyle of femur", "lateral condyle of femur", "medial condyle of femur"], "unordered"],
  // "6 tibula fibula features" : [[ "MCT", "LCT", "TT", "MM", "HF", "LM"], ["medial condyle of tibia", "lateral condyle of tibia", "tibial tuberosity", "medial malleolus", "head of fibula", "lateral malleolus"], "unordered"],
  // "11 ankle/foot bones" : [["C", "T", "N", "C", "LC", "MC", "IC", "M", "PP", "MP", "DP"], ["calcaneus", "talus", "navicular", "cuboid", "lateral cuneiform", "medial cuneiform", "intermediate cuneiform", "metatarsal 1", "proximal phalanx of foot", "middle phalanx of foot", "distal phalanx of foot"], "unordered"],
  // "7 vertebra features" : [["VB", "D", "SP", "TP", "SAP", "IAP", "VF"], ["vertebral body", "dens", "spinous process", "transverse process", "superior articular process", "inferior articular process", "vertebral foramen"], "unordered"],
  // "9 vertebral regions and special vertebrae" : [["CV", "TV", "LV", "SV", "S", "C", "At", "Ax", "Clong"], ["cervical vertebrae", "thoracic vertebrae", "lumbar vertebrae", "sacral vertebrae", "sacrum", "coccyx", "atlas", "axis", "C7"], "unordered"],
  // "10 skull bones" : [["F", "M", "O", "S", "V", "Z", "N", "M", "T", "P"], ["frontal", "mandible", "occipital", "sphenoid", "vomer", "zygomatic", "nasal", "maxilla", "temporal", "parietal"], "unordered"],
  // "5 thorax features" : [["M", "BS", "XP", "R", "C"], ["manubrium", "body of sternum", "xiphoid process", "rib", "clavicle"], "unordered"],
  // "6 scapula features" : [["GF", "CP", "AP", "SS", "PS", "AS"], ["glenoid fossa", "coracoid process", "acromion process", "spine of scapula", "posterior scapula", "anterior scapula"], "unordered"]
  // "4 Fibrous Joint Types" : [["G", "S", "I", "SD"], ["gomphosis", "sutre", "interosseus", "syndesmosis"], "unordered"],
  // "4 Cartilaginous Joint Types" : [["Sn", "Sy"], ["synchondrosis", "symphysis"], "unordered"],
  // "4 Synovial Joint Types" : [["S", "B", "C", "P", "H", "Pl"], ["saddle", "ball socket", "condylar", "pivot", "hinge", "plane"], "unordered"],
  // "2 Lateral Leg Muscles" : [["FPL", "FPB"], ["fibularis peroneus longus", "fibularis peroneus brevis"], "unordered"],
  // "4 Anterior Leg Muscles" : [["TA", "EDL", "EHL", "FPT"], ["tibialis anterior", "extensor digitorum longus", "extensor hallucis longus", "fibularis peroneus tertius"], "unordered"],
  // "6 Posterior Leg Muscles (superior then deep)" : [["G", "P", "S", "TP", "FDL", "FHL"], ["gastrocnemius", "plantaris", "soleus", "tibialis posterior", "flexor digitorum longus", "flexor hallucis longus"], "unordered"],
  // "4 Posterior Thigh & knee muscles" : [["BF", "ST", "SM", "P"], ["biceps femoris", "semitendinosis", "semimembranosus", "popliteus"], "unordered"],
  // "5 Medial Thigh Muscles" : [["AM", "G", "AL", "AB", "P"], ["adductor magnus", "gracilis", "adductor longus", "adductor brevis", "pectineus"], "unordered"],
  // "5 Anterior Thigh Muscles" : [["S", "RF", "VM", "VI", "VL"], ["sartorius", "rectus femoris", "vastus medialis", "vastus intermedius", "vastus lateralis"], "unordered"],
  // "3 Thigh Wrappers" : [["FL", "IT", "TFL"], ["fascia lata", "iliotibial band", "tensor fascia latae"], "unordered"],
  // "3 Thenar Muscles and 3 Hypothenar Muscles" : [["OP", "APB", "FPB", "ODM", "ADM", "FDMB"], ["opponens pollicis", "abductor pollicis brevis", "flexor pollicis brevis", "opponens digiti minimi", "abductor digiti minimi", "flexor digiti minimi brevis"], "unordered"],
  // "3 Intrinsic Muscles Random" : [["IP", "ID", "L"], ["interossei palmar", "interossi dorsal", "lumbricals"], "unordered"],
  // "4 Muscles that Move Arm" : [["TM", "C", "BB", "TB"], ["teres major", "coracobrachialis", "biceps brachii", "triceps brachii"], "unordered"],
  // "4 Rotator Cuff Muscles" : [["S", "I", "TM", "SS"], ["supraspinatus", "infraspinatus", "teres minor", "subscapularis"], "unordered"],
  "8 Trunk Muscles" : [["S", "D", "EO", "IO", "RA", "TA", "PM", "I"], ["sternocleidomastoid", "diaphragm", "external oblique", "internal oblique", "external oblique", "rectus abdominus", "transverse abdominus", "psoas major", "iliacus"], "unordered"],
  "3 Gluteus Muscles + 2 Outside Things" : [["GM", "GM", "GM", "IT", "TFL"], ["gluteus maximus", "gluteus medius", "gluteus minimus", "iliotibial tract", "tensor fasciae", "latae"], "unordered"],
  "13 Thigh Muscles" : [["S", "RF", "VM", "VL", "VI", "G", "P", "AB", "AL", "AM", "BF", "ST", "SM"], ["sartorius", "rectus femoris", "vastus medialis", "vastus lateralis", "vastus intermedius", "gracilis", "pectineus", "adductor brevis", "adductor longus", "adductor magnus", "biceps femoris", "semitendinosus", "semimembranosus"], "unordered"],
  "7 Posterior Leg Muscles" : [["P", "G", "S", "Pl", "TP", "FDL", "FHL"], ["popliteus", "gastrocnemius", "soleus", "plantaris", "tibialis posterior", "flexor digitorum longus", "flexor hallucis longus"], "unordered"],
  "3 Anterior Leg Muscles" : [["TA", "EDL", "EHL", ""], ["tibialis anterior", "extensor digitorum longus", "extensor hallucis longus"], "unordered"],
  "3 Lateral Leg Muscles" : [["FL", "FB", "FT"], ["fibularis longus", "fibularis brevis", "fibularis teritius"], "unordered"],
  "8 Blood Vessels Near Heart" : [["SVC", "IVC", "A", "PA", "PV", "B", "LS", "LC"], ["superior vena cava", "inferior vena cava", "aorta", "pulmonary arteries", "pulmonary veins", "brachiocephalic artery", "left subclavian artery", "left common carotid artery"], "unordered"],
  "10 Heart Structures" : [["RA", "LA", "RV", "LV", "PV", "TV", "BV", "AV", "PM", "CT"], ["left atrium", "right atrium", "right ventricle", "left ventricle", "pulmonary valve", "tricuspid valve", "bicuspid valve", "aortic valve", "papillary muscle", "chordae tendinae", "bicuspid valve"], "unordered"],
  "12 Brain Structures" : [["F", "P", "O", "TL", "T", "H", "M", "P", "MO", "Cl", "AV", "Cb"], ["frontal lobe", "parietal lobe", "occipital lobe", "temporal lobe", "thalamus", "hypothalamus", "midbrain", "pons", "medulla oblongata", "cerebellum", "arbor vitae", "cerebrum"], "unordered"],
  "15 Digestive System Structures" : [["S", "GO", "D", "DD", "J", "I", "C", "L", "G", "P", "A", "AC", "TC", "DC", "SC"], ["stomach", "greater omentum", "diaphragm", "duodenum", "jejunum", "ileum", "cecum", "liver", "gallbladder", "pancreas", "appendix", "ascending colon", "transverse colon", "descending colon", "sigmoid colon"], "unordered"]
}