export const tissuesA = {
  "tissues" : "groups of cells that are similar in structure & have common related function",
  "histology" : "the study of tissues",
  "microscopic anatomy" : "the anatomy branch above histology",
  "epithelial" : "type of tissue that protects",
  "connective" : "type of tissue that supports",
  "muscle" : "type of tissue that helps movement",
  "nervous" : "type of tissue that controls",
  "covering epithelium" : "forms outer layer of skin & internal structures - sounds like top layer",
  "lining epithelium" : "forms outer layer of skin & internal structures - sounds like internal layer",
  "stomach lining" : "an internal place where you'll find covering epithelium cells",
  "glandular epithelium" : "forms glands of body",
  "skin" : "a type of lining epithelial that protects us from outside world",
  "barrier muscle" : "epithelial cells line the inside of the stomach to serve as a _____ to protect the organ's _____",
  "salivary gland" : "gland in mouth made up of glanular epithelium cells",
  "sweat gland" : "gland that helps cool certain areas of the body",
  "boundary" : "primary purpose of epithelial cells is to form a ____ between two environments",
  "physical protection" : "key function of epithelial cells",
  "basement membrane" : "dense layer of extracellular matrix that lines most human tissues",
  "lumen" : "opening in a exocrine gland",
  "absorption" : "when things cross over epithelial barrier",
  "selective barrier" : "key function of absorption-based epithelial cells",
  "sensation" : "paSs",
  "bent" : "what helps cillia know they need to tell the body about a substance nearby",
  "tastebuds" : "an example of epithelial sensory receptors in mouth",
  "sensory receptors" : "to facilitate sensation, epithelial cells make up ____",
  "photoreceptors" : "receptors in eye",
  "rods cones" : "2 specialized epithelia in eye",
  "glands" : "where secretion occurs",
  "secretion" : "pasS",
  "endocrine" : "the type of gland that secretes products directly into the bloodstream",
  "exocrine" : "secrets products into ducts",
  "pancreas" : "endocrine gland that produces insulin",
  "thyroid" : "important endocrine gland in neck",
  "pituitary" : "important endocrine gland in head",
  "metabolism" : "important whole body activity that epithelial cells can effect",
  "full body" : "how far is the impact of endocrine gland secretions",
  "ring" : "general shape of glands",
  "thicker" : "the basement membrane in exocrine gland tissues is ____ than in endocrine gland tissues",
  "local control" : "term that describes the area exocrine gland cells can serve",
  "apical surface" : "free part of epithelial tissue exposed to exterior environment or cavity of organ",
  "microvilli cilia" : "structures that are commonly on the apical surface of epithelial cells",
  "basal surface" : "anchored lower surface of epithelial cell",
  "basal lamina" : "adhesive sheet beneath basal surface; joins epithelial tissue to connective tissue; superficial part of basement membrane",
  "reticular lamina" : "deeper, second layer of basement membrane in cases where epethelial cells are attached to connective tissue",
  "filter" : "basal lamina's function",
  "sheets" : "epithelial cells tend to be found as ____",
  "connective tissue" : "epithelial cells usually sit on top of and are supported by _____",
  "nearby blood vessels" : "where do epithelial cells get nutrients from",
  "avascular" : "are epithelial cells vascular or avascular",
  "innervated" : "are epithelial cells innervated or aneural",
  "high" : "do epithelial cells have low or high regerative capacity",
  "follicle" : "small anatomical cavity found in endocrine glands that excretions diffuse accross",
  "cell division" : "how epithelial cells replace themselves when damaged by toxins or friction",
  "simple" : "single layer of cells",
  "stratified" : "multple layers of cells",
  "squamous" : "flat cell shape",
  "cuboidal" : "square cell shape",
  "columnar" : "tall cell shape",
  "more protection" : "more layers =",
  "single layer" : "a trait of some tissues that makes it easier for substances to pass through",
  "simple squamous" : "a thin, delicate tissue designed for easy transport of molecules across",
  "small intestine" : "a place where you can find lots of simple squamous epithelium",
  "alveoli" : "a place in longs where you will find lots of simple squamous epithelium",
  "endothelium" : "special simple squamous epitheliem in blood vessels",
  "mesothelium" : "special simple squamous epithelium in abdominal cavity",
  "simple cuboidal" : "tissue specialized in absorbing fluid",
  "nephron" : "a place in kidney where simple cuboidal cells can be found",
  "nonciliated simple columnar" : "single-layer tall cells that have microvilli to increase surface area",
  "small intestine peritonium" : "a place where you can find lots of nonciliated simple columnar cells",
  "ciliated simple columnar" : "single layer of tall cells covered in hair-like structures",
  "goblet cells" : "produce mucus",
  "uterine tube" : "a place where you can find ciliated simple columnar cells",
  "cilia" : "hairlike structures",
  "stratified squamous" : "many layers of thin cells",
  "vagina" : "a place with stratified squamous cells",
  "dead" : "trait of top-layer cells that don't have nuclei in statified squamous tissue",
  "basal" : "what surface to stratified cells regenerate from",
  "stratified cuboidal" : "many layers of dice-shaped cells",
  "esophagus" : "an area where you can find stratified cuboidal cells",
  "overlap" : "why doesn't stratified cuboidal or columnar protect as much as stratified squamous",
  "stratified columnar" : "many layers of tall cells",
  "pharynx" : "a place where you can find stratified columnar cells in its lining",
  "pseudostratified columnar" : "tissue looks like it's in multiple layers, but every cell is still touching basement membrane",
  "trachea" : "a place where you can find pseudostratified columnar cells",
  "transitional epithelium" : "stratified layers of cells that change in shape depending on where they are & what loads are applied to them",
  "bladder" : "organ that contains transitional epithelium cells",
  "urinary bladder" : "a place in the body where the physical protection trait of epithelial cells is important",
  "kidney" : "a place in the body where there are lots of epithelial cells engaged in absorption",

}

export const tissuesB = {
  "support" : "primary purpose of connective tissue",
  "mesenchyme" : "what connective tissue originally developed from",
  "bone support" : "'support' function in body, provides framework (incl. 'support')",
  "cartilage" : "'support' function in body, preventing structures such as the trachea & windpipe from collapsing",
  "fibrocartilage" : "'support' function in body, structure on intervertebral disc that helps hold load",
  "tendon" : "'binding' function in body, attaches muscle to bone",
  "adipose" : "'storage' function in body, stores energy as fat",
  "bone storage" : "'storage' function in body, stores calcium, fat & blood cells, (incl. 'storage')",
  "blood" : "'transport' function in body, circulates things like nutrients & waste",
  "lymph" : "'transport' function in body, circulates fluid",
  "bone protection" : "'protection' function in body, protects organs (incl. 'protection')",
  "fat pads" : "'protection' function in body, on feet & palms",
  "white blood cells" : "'protection' function in body, protect body from pathogens",
  "bone marrow" : "where many white blood cells are made",
  "cells, ground substance, fibers" : "3 structural elements of connective tissue",
  "macrophages" : "destroy bacteria & cell debris by phagocytosis",
  "fibroblasts" : "move through connective tissue and secrete fibers & ground substance",
  "mast cells" : "produce histamine which dialates small blood vessels during inflammation & kills bacteria; lots along blood vessels",
  "plasma cells" : "secrete antibodies that attack & neutralise foreign substances",
  "adipocytes" : "cells that store fats; found below skin & around organs",
  "eosinophils" : "white blood cells that migrate to sites of parasitic infection & allergic respondes",
  "neutrophils" : "white blood cells that migrate to sites of infection & destroy microbes by phagocytosis",
  "defence cells" : "blanket term for cells that break down invading pathogens",
  "ground substance" : "nonliving substance that binds/supports cells and fibers & provides medium for substance exchange between blood and cells",
  "elastic fibers" : "stretchable, but strong fibers made of proteins, elastin & fibrillin",
  "protein, elastin, fibrillin" : "substances that make up elastic fibers",
  "reticular fibers" : "provide support in blood vessel walls & form branch networks aroud cells",
  "collagen glycoprotein" : "what substances make up reticular fibers",
  "white" : "colour of reticular and collagen fibers",
  "lattice" : "word that describes the pattern of reticular fibers",
  "collagen fibers" : "fibers made up of strong, flexible bundles of a specific protein",
  "collagen" : "most abundant protein in body",
  "extracellular matrix" : "ground substance + fibers; determines the function of connective tissue",
  "gelatinous" : "a word that describes the consistency of ground substance",
  "fibers" : "structural element of connective tissue that adds integrity to the tissue",
  "yellow" : "color of elastic fibers",
  "elastic" : "type of fibers found in skin, blood vessels & lung tissue",
  "loose dense" : "two types of connective tissue proper",
  "areolar" : "least specialized type of loose connective tissue",
  "holds water" : "common trait of areolar tissue",
  "areolar tissue" : "tissue that makes up skin and lining of capillaries (incl. 'tissue')",
  "fibroblast defence adipose" : "three types of cells that make up areolar tissue",
  "adipose tissue" : "tissue where primary cell type is lipid (incl. 'tissue')",
  "adipose location" : "tissue that can be found in female breasts, around organs (incl. 'location')",
  "reticular" : "tissue that contains predominantly ____ fibers; very thin connective tissue fibers",
  "reticular tissue" : "tissue found in hollow organs, like liver, spleen & lymph nodes",
  "sponge" : "comparison for reticular tissue that explains form and function",
  "dense" : "type of connective tissue proper that has more fibers than loose connective tissue",
  "less more" : "dense connective tissue has ____ ground substance and ____ fibers than loose connective tissue",
  "regular" : "dense connective tissue proper with lots of aligned, densly packed collagen fibers",
  "one" : "how many directions are regular tissues strong in",
  "ligament tendon" : "two structures that contain regular connective tissue",
  "poor" : "do regular connective tissues have poor or ample blood supply",
  "irregular" : "dense connective tissue with an irregular/mesh pattern",
  "many" : "how many directions of strength fo irregular connective tissues have",
  "irregular tissue" : "tissue found in skin, lining around bone/cartilage (periosteum, perichondrium) (incl. 'tissue')",
  "elastic tissue" : "dense connective tissue made of collagen & elstic fibers that stretch & recoil (incl. 'tissue')",
  "elastic tissue location" : "tissue found in arteries, ligamentum flava, aorta (incl. 'tissue location')",
  "membrane" : "substance made of loose or dense connective tissue",
  "epithelium, connective tissue, basement membrane" : "three elements that make up membrane",
  "cutaneous membrane" : "skin",
  "epidermis dermis" : "the two layers of the skin (epithelia + connective tissue)",
  "mucous" : "membrane made of epithelia, loose connective tissue and goblet cells",
  "columnar" : "cell shape of most mucous membranes",
  "mucous membrane" : "substance that lines smill inestine and inside of organs (respiratory, urinary, etc) (incl. 'membrane')",
  "serous" : "membrane made of simple epithelia (often squamous or cuboidal) and areolar connective tissue",
  "serous membrane" : "membrane that procuces a thin, watery fluid that removes friction between two layers (incl. 'membrane')",
  "serous location" : "membrane that surrounds lungs & heart (incl. 'membrane')",
  "synovial" : "membrane that includes ______ cells and loose connective tissue",
  "synovial substance" : "substance that's technically not a membrane, but similar (incl. 'substance')",
  "synovial location" : "substance that lines joint cavities & secretes fluid (incl. 'location')",
  "chondrocyte" : "cartilage cell",
  "chondroblast" : "cell that makes collagen, elastic fibers and ground substance (like fibroblasts)",
  "chondroitin sulfate" : "substacne in cartilage ground substance that helps it take a lot of force/stress per area",
  "perichondrium" : "dense layer of connective tissue covering cartilage",
  "cartilage tissue" : "tissue that provides cushioning & allows bones to slide past each other will less friction (incl. 'tissue')",
  "more water" : "difference between ground substance in cartilage and other connective tissues",
  "hyaline" : "most common type of cartilage",
  "articular cartilage" : "type of hyaline that is at the ends of most long bones (gives them smooth surface)",
  "has articular cartilage doesn't" : "most hylaline ___ perichondrium, but _______",
  "collagen fiber" : "hyaline has a high concentration of _____ (no 's')",
  "skeletal system" : "what is hyaline the precurser to",
  "ribs sternum" : "two places where hyaline is found",
  "elastic cartilage" : "more uncommon cartilage, with the most give (stretchiest) and also the least resilient (incl. 'cartilage')",
  "collagen elastic" : "two substances that make up elastic cartilage",
  "has" : "elastic cartilage ____ outer perichondrium",
  "oracle of ear"  : "location where elastic cartilage can be found",
  "fibrocartilage cartilage" : "cartilage that's found in great quantity, but only in specific places (incl. 'cartilage')",
  "toughest" : "fibrocartilage is the ____ of the cartilages",
  "parallel rows" : "how are chondrocytes & collagen fibers arranged in fibrocartilage",
  "no" : "does fibrocartilage have perichondrium",
  "intervertebral disc" : "location where fibrocartilage can be found",
  "compression" : "what does fibrocartilage resist",
  "compact" : "the harder type of bone",
  "spongy" : "the type of bone where things are stored",
  "bone" : "connective tissue that supports, protects and houses blood-forming tissue",
  "collagen calcium" : "two important components of bone",
  "reticular elastic" : "two types of fibers not present in bone",
  "leukocytes" : "white blood cells",
  "erythrocytes" : "red blood cells"
}