export const tissuesA = {
  "tissues" : "groups of cells that are similar in structure & have common related function",
  "histology" : "the study of tissues",
  "microscopic anatomy" : "the anatomy branch above histology",
  "epithelial" : "type of tissue that protects",
  "connective" : "type of tissue that supports",
  "muscle" : "type of tissue that helps movement",
  "nervous" : "type of tissue that controls",
  "covering epithelium" : "forms outer layer of skin & internal structures - sounds like top layer",
  "lining epithelium" : "forms outer layer of skin & internal structures - sounds like internal layer",
  "glandular epithelium" : "forms glands of body",
  "skin" : "what protects us from outside world",
  "barrier muscle" : "epithelial cells line the inside of the stomach to serve as a _____ to protect the organ's _____",
  "saliva" : "substance secreted by glands",
  "boundary" : "primary purpose of epithelial cell; what they form",
  "physical protection" : "key function of epithelial cells",
  "basement membrane" : "dense layer of extracellular matrix that lines most human tissues",
  "lumen" : "opening in a exocrine gland",
  "absorption" : "pAss",
  "selective barrier" : "key function of absorption-based epithelial cells",
  "sensation" : "paSs",
  "tastbuds" : "an example of epithelial sensory receptors in mouth",
  "sensory receptors" : "to facilitate sensation, epithelial cells make up ____",
  "photoreceptors" : "receptors in eye",
  "rods cones" : "2 specialized epithelia in eye",
  "glands" : "where secretion occurs",
  "secretion" : "pasS",
  "endocrine" : "the type of gland that secretes products directly into the bloodstream",
  "exocrine" : "secrets products into ducts",
  "pancreas" : "exocrine gland that produces insulin",
  "local" : "how far is the impact of exocrine glad secretions",
  "thyroid" : "important endocrine gland in neck",
  "metabolism" : "important whole body activity that epithelial cells can effect",
  "full body" : "how far is the impact of endocrine gland secretions",
  "ring" : "general shape of glands",
  "thicker" : "the basement membrane in exocrine gland tissues is ____ than in endocrine gland tissues",
  "local control" : "term that describes the area epithelial cells can serve",
  "apical surface" : "free surface exposed to exterior environment or cavity of organ",
  "microvilli cilia" : "structures that are commonly on the apical surface of epithelial cells",
  "basal surface" : "anchored lower surface of epithelial cell",
  "basal lamina" : "adhesive sheet beneath Basal Surface; joins epithelial tissue to connective tissue; superficial part of basement membrane",
  "reticular lamina" : "deeper, second layer of basement membrane in cases where epethelial cells are attached to connective tissue",
  "filter" : "basal lamina's function",
  "sheets" : "epithelial cells fit closely together to form continuous ____",
  "connective tissue" : "epithelial cells usually sit on top of and are supported by _____",
  "avascular" : "are epithelial cells vascular or avascular",
  "innervated" : "are epithelial cells innervated or aneural",
  "high" : "do epithelial cells have low or high regerative capacity",
  "follicle" : "small anatomical cavity found in endocrine glands",
  "cell division" : "how epithelial cells replace themselves when damaged by toxins or friction",
  "simple" : "single layer of cells",
  "stratified" : "multple layers of cells",
  "squamous" : "flat cell shape",
  "cuboidal" : "square cell shape",
  "columnar" : "tall cell shape",
  "more protection" : "more layers =",
  "single layer" : "trait of some tissues that makes it easier for substances to pass through",
  "simple squamous" : "thin, delicate tissue specialised in moving molecules across",
  "small intestine" : "a place where you can find lots of simple squamous epithelium",
  "endothelium" : "special simple squamous epitheliem in blood vessels",
  "mesothelium" : "special simple squamous epithelium in abdominal cavity",
  "simple cuboid" : "tissue specialized in absorbing fluid",
  "nonciliated simple columnar" : "single-layer tall cells that have microvilli to increase surface area",
  "ciliated simple columnar" : "single layer of tall cells covered in hair-like structures",
  "goblet cells" : "produce mucus",
  "cilia" : "hairlike structures",
  "stratified squamous" : "many layers of thin cells",
  "dead" : "trait of top-layer cells that don't have nuclei in statified squamous tissue",
  "basal" : "what surface to stratified cells regenerate from",
  "stratified cuboidal" : "many layers of dice-shaped cells",
  "overlap" : "why doesn't stratified cuboidal or columnar protect as much as stratified squamous",
  "stratified columnar" : "many layers of tall cells",
  "pseudostratified columnar" : "tissue looks like it's in multiple layers, but every cell is still touching basement membrane",
  "transitional epithelium" : "stratified layers of cells that change in shape depending on where they are & what loads are applied to them",
  "bladder" : "organ that contains transitional epithelium cells"
}